import type { ModuleDomain } from '@contracts';

// Closed category→domain table for HOI4 equipment modules. Modules self-classify
// by their `category` value — no archetype resolution — so the table is the whole
// classifier. O(1) category→domain lookup via the const object; a category absent
// from the table resolves to 'unclassified' at the call site. Keys are globally
// alphabetical per R-CODE-9; the domain is the only payload.
export const MODULE_CATEGORY_DOMAIN = {
  armament_type: 'land',
  armor_plate: 'air',
  armor_type: 'land',
  bombs: 'air',
  carrier_ship_engine: 'naval',
  cruiser_ship_engine: 'naval',
  defensive_main_weapon: 'air',
  engine: 'air',
  engine_type: 'land',
  fixed_main_weapon: 'air',
  heavy_aircraft_armament: 'air',
  heavy_ship_engine: 'naval',
  light_aircraft_armament: 'air',
  light_ship_engine: 'naval',
  medium_aircraft_armament: 'air',
  ship_airplane_launcher: 'naval',
  ship_anti_air: 'naval',
  ship_carrier_armor: 'naval',
  ship_cruiser_armor: 'naval',
  ship_deck_space: 'naval',
  ship_depth_charge: 'naval',
  ship_extra_fuel_tanks: 'naval',
  ship_fire_control_system: 'naval',
  ship_heavy_armor: 'naval',
  ship_heavy_battery: 'naval',
  ship_light_battery: 'naval',
  ship_medium_battery: 'naval',
  ship_mine_layer: 'naval',
  ship_mine_layer_sub: 'naval',
  ship_mine_warfare: 'naval',
  ship_radar: 'naval',
  ship_secondaries: 'naval',
  ship_sonar: 'naval',
  ship_sub_snorkel: 'naval',
  ship_super_heavy_armor: 'naval',
  ship_super_heavy_battery: 'naval',
  ship_torpedo: 'naval',
  ship_torpedo_sub: 'naval',
  special_armament: 'air',
  special_type: 'land',
  sub_ship_engine: 'naval',
  suspension_type: 'land',
  turret_type: 'land',
} as const satisfies Record<string, Exclude<ModuleDomain, 'unclassified'>>;
