// The autogenerated-token rule, grounded against BICE (ledger `L-023`, report in
// `docs/grounding/ZMT-50-technology-loc-grounding.md`). ADR 028 decision 4 fixes
// the PIVOT — stale loc cleanup fires only for autogenerated tokens, because only
// they move — and deliberately leaves the rule itself to be read from the corpus.
//
// The convention, measured over all 2 670 BICE technology tokens: `[a-z0-9_]`,
// `_`-separated, never leading-digit (0 of 2 670), 2.6 % uppercase and all of those
// vanilla-inherited. Tokens are AUTHORED, not slugs: only 222 of the 2 408 tokens
// that carry a name key (9.2 %) equal `normalize(name)` — `tech_bf_110_fighter_
// equipment_1` is "Bf 110 B", `tech_raf` is "Royal Air Force". Both states are real
// on disk and split by tech family: 35 of 40 `air_doctrine_folder` techs are
// autogen-shaped, 0 of 638 equipment-style air techs are.

const AUTOGEN_FALLBACK_PREFIX = 'tech_';

// Whether `token` is the autogenerated token for `publicName` — the ADR 028
// decision 4 pivot, decided by SHAPE because nothing on disk records how a token
// was chosen. A token that reproduces the normalization of its own public name
// moves when that name changes; any other token is the user's and is stable.
// Getting this wrong in either direction is a data defect (ADR 028 Consequences):
// autogen-not-cleaned orphans a loc key, custom-treated-as-autogen destroys one.
export function isAutogeneratedToken(
  token: string,
  publicName: string,
): boolean {
  return (
    publicName.trim() !== '' && normalizeTechnologyToken(publicName) === token
  );
}

// Turns a user-typed public name into a token in the corpus's convention.
// Diacritics are folded rather than dropped so "Curtiss Hawk 75-Ö" yields
// `curtiss_hawk_75_o`, not `curtiss_hawk_75_`.
export function normalizeTechnologyToken(publicName: string): string {
  const folded = publicName
    .normalize('NFKD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase();
  const token = folded.replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  // No BICE token begins with a digit, and an empty token is not a token at all;
  // both fall back to the corpus's dominant `tech_` prefix.
  return token === '' || /^\d/.test(token)
    ? `${AUTOGEN_FALLBACK_PREFIX}${token}`
    : token;
}

// Collision handling (L-023 requires it be handled, not asserted): suffix `_2`,
// `_3`, … until free. SUFFIX, NEVER REJECT — 64 BICE display names are shared by
// two or more technologies, so a normalized token collides on real data, and 152
// BICE token families already disambiguate with exactly this trailing `_<n>`
// counter. `taken` excludes `self` so re-saving an unchanged name is not treated
// as colliding with itself.
export function resolveTokenCollision(
  candidate: string,
  taken: readonly string[],
  self: null | string = null,
): string {
  const occupied = new Set(taken.filter((id) => id !== self));
  if (!occupied.has(candidate)) return candidate;
  let suffix = 2;
  while (occupied.has(`${candidate}_${String(suffix)}`)) suffix += 1;
  return `${candidate}_${String(suffix)}`;
}
