import { describe, expect, it } from 'vitest';

import {
  isAutogeneratedToken,
  normalizeTechnologyToken,
  resolveTokenCollision,
} from './technology-token.util';

// The L-023 autogen rule, asserted against REAL BICE token↔name pairs (report:
// `docs/grounding/ZMT-50-technology-loc-grounding.md`). The pairs are cited, not
// invented: each row below is a measured `common/technologies/*.txt` token and its
// `localisation/english/*.yml` name value.

describe('normalizeTechnologyToken — the BICE token convention', () => {
  it.each([
    ['Air Superiority', 'air_superiority'],
    ['Bf 110 B', 'bf_110_b'],
    ['Royal Air Force', 'royal_air_force'],
    ['Voyenno-Vozdushnye Sily', 'voyenno_vozdushnye_sily'],
    ['Supermarine Spitfire', 'supermarine_spitfire'],
    ['Panzerschiffe Design', 'panzerschiffe_design'],
    ['Avro Lancaster GR.3/MR.3', 'avro_lancaster_gr_3_mr_3'],
    ['Caproni Ca.313', 'caproni_ca_313'],
  ])('normalizes %j to %j', (name, token) => {
    expect(normalizeTechnologyToken(name)).toBe(token);
  });

  it('folds diacritics rather than dropping the character', () => {
    expect(normalizeTechnologyToken('Bloch MB.151 Écureuil')).toBe(
      'bloch_mb_151_ecureuil',
    );
  });

  it('never produces a leading-digit token — no BICE token has one', () => {
    expect(normalizeTechnologyToken('262 Schwalbe')).toBe('tech_262_schwalbe');
  });

  it('produces a usable token from a name with no alphanumerics', () => {
    expect(normalizeTechnologyToken('---')).toBe('tech_');
  });
});

describe('isAutogeneratedToken — the ADR 028 decision 4 pivot', () => {
  // 35 of 40 BICE air-doctrine techs are autogen-shaped; 0 of 638 equipment-style
  // air techs are. Both branches are reachable on real data, so neither may be
  // treated as the universal case.
  it('is true for a doctrine tech whose token reproduces its name', () => {
    expect(isAutogeneratedToken('air_superiority', 'Air Superiority')).toBe(
      true,
    );
  });

  it.each([
    ['tech_bf_110_fighter_equipment_1', 'Bf 110 B'],
    ['tech_raf', 'Royal Air Force'],
    ['soviet_air_tech', 'Voyenno-Vozdushnye Sily'],
    ['tech_spitfire_equipment_1', 'Supermarine Spitfire'],
  ])('is false for the authored token %j ("%s")', (token, name) => {
    expect(isAutogeneratedToken(token, name)).toBe(false);
  });

  it('is false when the technology has no localised name at all', () => {
    // The 35 base `air_techs_folder` techs: no BICE loc key, name from vanilla.
    // With nothing to compare against, the token is treated as the user's — the
    // safe direction, since the other one DESTROYS a key (ADR 028 Consequences).
    expect(isAutogeneratedToken('fighter1', '')).toBe(false);
  });
});

describe('resolveTokenCollision — suffix, never reject', () => {
  // 64 BICE display names are shared by two or more technologies, so a normalized
  // token collides on real data; 152 BICE token families already disambiguate with
  // exactly this trailing `_<n>` counter.
  it('returns the candidate untouched when it is free', () => {
    expect(resolveTokenCollision('avro_anson', ['other_tech'])).toBe(
      'avro_anson',
    );
  });

  it('suffixes _2 on the first collision', () => {
    expect(resolveTokenCollision('avro_anson', ['avro_anson'])).toBe(
      'avro_anson_2',
    );
  });

  it('walks the suffix until free rather than rejecting', () => {
    expect(
      resolveTokenCollision('avro_anson', [
        'avro_anson',
        'avro_anson_2',
        'avro_anson_3',
      ]),
    ).toBe('avro_anson_4');
  });

  it('does not treat the technology itself as a collision', () => {
    expect(
      resolveTokenCollision(
        'air_superiority',
        ['air_superiority'],
        'air_superiority',
      ),
    ).toBe('air_superiority');
  });
});
