import {
  EntityLocBatchOperation,
  EntityLocCreateBatchOperation,
} from '@contracts';
import { EntityFormLocalisationContext } from '@r-core';

import { technologyNameLocKey } from './technology-loc-keys.util';

// The version suffix a newly inserted technology key carries. Every technology
// name key cited in the ZMT-50 grounding is `:0`.
const INSERT_VERSION = '0';

// What a save must do to localisation for one public-name edit (ADR 028 D3).
export interface TechnologyLocPlan {
  // Loc operations, one per target file, each carrying its file's ordered deltas —
  // optionally preceded by that file's create-if-absent seed when the target is the
  // user's chosen save target (ADR 029 decision 3). There is deliberately NO
  // `renameTo` anywhere on this path: the edit path issues zero block renames (see
  // below), and making that structurally impossible is a stronger guarantee than a
  // convention the next edit could quietly break — which is why the operation type
  // widens only to the two loc members, not to the whole batch union.
  readonly operations: readonly (
    | EntityLocBatchOperation
    | EntityLocCreateBatchOperation
  )[];
}

// The open-time localisation state of one technology, projected from the host's
// resolved lookup.
export interface TechnologyLocSnapshot {
  readonly context: EntityFormLocalisationContext;
  readonly token: string;
}

// Computes the localisation half of a technology save.
//
// THE TOKEN IS FROZEN ON THE EDIT PATH (ZMT-50 review, Q89/Q90). ADR 028 decision
// 4 says an autogenerated token regenerates when the public name changes, and that
// the stale loc keys are then deleted and re-inserted under the new token. That
// cannot be done safely from HERE: the token is the technology's identity, so
// regenerating it orphans every inbound reference — `path.leads_to_tech`,
// `dependencies`, `token:<id>` in effect blocks, the `GFX_<id>_medium` sprite name,
// and other mods' overrides — and the form cannot know that reference set from
// where it sits. Rewriting them all, mod-wide and atomically, IS move-entity
// (ledger L-011, expanded to a worker-driven reference cascade); it is deferred and
// gets its own ADR. So on edit the token never moves and the plan is the same
// shape for both token states:
//
//   - the key written is ALWAYS `technologyNameLocKey(<current token>)`;
//   - an existing, editable key → loc `set`;
//   - no key, or a key we may not write (vanilla) → loc `insert` into the default
//     target. This is the third case ADR 028 D4 did not enumerate and the COMMON
//     one on the canvas's own folder: none of the 35 base `air_techs_folder`
//     technologies has a BICE loc key — their names live in vanilla (grounding §4).
//
// The autogen-vs-custom distinction is NOT dead — it decides how a token is derived
// in the first place, which is Add's concern (`technology-token.util.ts`), where a
// brand-new technology has no inbound references to break.
export function computeTechnologyLocPlan(
  snapshot: TechnologyLocSnapshot,
  publicName: string,
  openTimePublicName: string,
): TechnologyLocPlan {
  const { context, token } = snapshot;
  const next = publicName.trim();
  if (next === openTimePublicName) return { operations: [] };

  const nameKey = technologyNameLocKey(token);
  const existing = context.entries.find((entry) => entry.key === nameKey);

  if (existing?.target != null && existing.permission === 'editable') {
    return {
      operations: [
        operation(existing.target, [
          { key: nameKey, kind: 'set', value: next },
        ]),
      ],
    };
  }

  // ADR 028 decision 6, closed by ZMT-57: the insert target is what
  // `resolveWriteTarget('locKey', …)` returned upstream — the user's chosen save
  // target when set, the derived default otherwise. Null still means the workspace
  // has no editable loc file, and the edit is dropped rather than guessed at.
  if (context.defaultTarget === null) return { operations: [] };
  const { defaultTarget, defaultTargetSeedLanguage } = context;
  return {
    operations: [
      // A chosen target may be a file the user named and never created, so its
      // create-if-absent seed leads the file's sequence (ADR 029 decisions 3 and 6).
      // Absent for the derived default, which keeps the unset path's batch exactly
      // the shape ZMT-50 shipped.
      ...(defaultTargetSeedLanguage === null
        ? []
        : [
            {
              format: 'locCreate' as const,
              language: defaultTargetSeedLanguage,
              modId: defaultTarget.modId,
              relativePath: defaultTarget.relativePath,
            },
          ]),
      operation(defaultTarget, [
        { key: nameKey, kind: 'insert', value: next, version: INSERT_VERSION },
      ]),
    ],
  };
}

// The technology's current localised public name, or '' when no source defines it
// (the base air tree, whose names live in vanilla — ZMT-50 grounding §4).
export function technologyPublicName(
  context: EntityFormLocalisationContext,
  token: string,
): string {
  const nameKey = technologyNameLocKey(token);
  return context.entries.find((entry) => entry.key === nameKey)?.value ?? '';
}

function operation(
  target: { readonly modId: string; readonly relativePath: string },
  deltas: EntityLocBatchOperation['deltas'],
): EntityLocBatchOperation {
  return {
    deltas,
    format: 'loc',
    modId: target.modId,
    relativePath: target.relativePath,
  };
}
