import {
  AppApiModel,
  EntityBatchWriteRequest,
  TechnologyEntity,
} from '@contracts';
import {
  EntityFormLocalisationContext,
  EntityFormValues,
  OBJECT_LIST_ITEM_INDEX_KEY,
  PropertyBagBlock,
} from '@r-core';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { TECHNOLOGY_FORM_DESCRIPTOR } from './technology-form-descriptor';

// ZMT-50 regression gates 2, 3 and 7 — the FORM half of the edit loop. It asserts
// the exact `EntityBatchWriteRequest` the descriptor emits; the main-side spec
// (`entity-mutation.batch.spec.ts`) consumes that same shape against a real
// scratch mirror, so the two meet at the wire contract.

const write = vi.fn();
const writeBatch = vi.fn();

const LOC_TARGET = {
  modId: 'bice',
  relativePath: 'localisation/english/research_l_english.yml',
};

// A doctrine-shaped technology: an AUTOGENERATED token (`air_superiority` ↔ "Air
// Superiority" — 35 of 40 BICE air-doctrine techs are this shape).
function entity(token = 'air_superiority'): TechnologyEntity {
  return {
    categories: [],
    dependencies: [],
    enableEquipmentModules: [],
    enableEquipments: [],
    enableSubunits: [],
    folders: [
      {
        position: [
          { key: 'x', symbol: { name: 'FTR_START' }, value: '5' },
          { key: 'y', value: '4' },
        ],
        scalars: [{ key: 'name', value: 'air_techs_folder' }],
      },
    ],
    paths: [],
    rootScalars: [{ key: 'research_cost', value: '2' }],
    subTechnologies: [],
    token,
    xor: [],
  };
}

function localisation(
  overrides: Partial<EntityFormLocalisationContext> = {},
): EntityFormLocalisationContext {
  return {
    defaultTarget: LOC_TARGET,
    defaultTargetSeedLanguage: null,
    entries: [
      {
        key: 'air_superiority',
        permission: 'editable',
        target: LOC_TARGET,
        value: 'Air Superiority',
        version: '0',
      },
    ],
    takenIds: ['air_superiority'],
    ...overrides,
  };
}

// `null` means "opened without loc context" (the ML file view). It cannot be
// `undefined`: passing `undefined` for an optional parameter re-triggers its
// default, which would silently test the with-context path instead.
function project(
  localisationContext: EntityFormLocalisationContext | null = localisation(),
  subject: TechnologyEntity = entity(),
) {
  return TECHNOLOGY_FORM_DESCRIPTOR.project(subject, {
    ...(localisationContext === null
      ? {}
      : { localisation: localisationContext }),
    modId: 'bice',
    relativePath: 'common/technologies/air_doctrine.txt',
    translate: (key) => key,
  });
}

// Open-time form values for the fixture, overridable per case.
function values(overrides: EntityFormValues = {}): EntityFormValues {
  return {
    __publicName: 'Air Superiority',
    categories: [],
    dependencies: [],
    enableEquipmentModules: [],
    enableEquipments: [],
    enableSubunits: [],
    folder: [
      {
        name: 'air_techs_folder',
        [OBJECT_LIST_ITEM_INDEX_KEY]: 0,
        position: { x: '5', y: '4' },
      },
    ],
    path: [],
    research_cost: '2',
    xor: [],
    ...overrides,
  };
}

beforeEach(() => {
  Object.defineProperty(window, 'api', {
    configurable: true,
    value: { entity: { write, writeBatch } } as unknown as AppApiModel,
    writable: true,
  });
});

afterEach(() => {
  vi.clearAllMocks();
});

describe('technology form — the public-name field (ADR 028 decision 3)', () => {
  it('renders the current localised name as a fixed field on the root block', () => {
    const root = project().blocks[0] as PropertyBagBlock;
    expect(root.members.mode).toBe('fixed');
    if (root.members.mode !== 'fixed') return;

    expect(root.members.fields[0]).toEqual({
      label: 'plugin.hoi4:technology.form.fields.publicName',
      spec: { name: '__publicName' },
      value: 'Air Superiority',
    });
  });

  it('is empty when no source defines the key (the base air tree — grounding §4)', () => {
    const root = project(localisation({ entries: [] }), entity('fighter1'))
      .blocks[0] as PropertyBagBlock;
    if (root.members.mode !== 'fixed') return;

    expect(root.members.fields[0].value).toBe('');
  });

  it('is absent entirely when the form is opened without loc context (the ML file view)', () => {
    const root = project(null).blocks[0] as PropertyBagBlock;
    if (root.members.mode !== 'fixed') return;

    expect(
      root.members.fields.some((field) => field.value === 'Air Superiority'),
    ).toBe(false);
    expect(root.members.fields[0].label).toBe(
      'plugin.hoi4:technology.form.fields.research_cost',
    );
  });
});

describe('technology form — the write is a cross-file batch (gates 2 and 3)', () => {
  it('never calls the single-file `entity.write` any more', async () => {
    await project().save(values({ research_cost: '9' }));

    expect(write).not.toHaveBeenCalled();
    expect(writeBatch).toHaveBeenCalledTimes(1);
  });

  it('carries the script delta unchanged — the same delta the single-file write carried (gate 3)', async () => {
    await project().save(values({ research_cost: '9' }));

    const request = writeBatch.mock.calls[0][0] as EntityBatchWriteRequest;
    expect(request.operations).toEqual([
      {
        deltas: [
          {
            added: [],
            block: null,
            changed: [{ key: 'research_cost', value: '9' }],
            removed: [],
          },
        ],
        entityName: 'air_superiority',
        format: 'script',
        modId: 'bice',
        relativePath: 'common/technologies/air_doctrine.txt',
      },
    ]);
  });

  it('commits the script edit and the loc edit as ONE batch (gate 2)', async () => {
    await project(
      localisation({
        entries: [
          {
            key: 'tech_spitfire_equipment_1',
            permission: 'editable',
            target: LOC_TARGET,
            value: 'Supermarine Spitfire',
            version: '0',
          },
        ],
      }),
      entity('tech_spitfire_equipment_1'),
    ).save(
      values({
        __publicName: 'Supermarine Spitfire Mk.V',
        research_cost: '9',
      }),
    );

    const request = writeBatch.mock.calls[0][0] as EntityBatchWriteRequest;
    expect(request.operations.map((operation) => operation.format)).toEqual([
      'script',
      'loc',
    ]);
    expect(request.operations[1]).toEqual({
      deltas: [
        {
          key: 'tech_spitfire_equipment_1',
          kind: 'set',
          value: 'Supermarine Spitfire Mk.V',
        },
      ],
      format: 'loc',
      modId: 'bice',
      relativePath: 'localisation/english/research_l_english.yml',
    });
  });

  // Gate 1 of the fix pass: the edit path issues ZERO block renames, for EITHER
  // token state. `air_superiority` is autogen-shaped — the state ADR 028 D4 said
  // would regenerate the token — so it is the case that would break if the freeze
  // regressed. A rename here would orphan every inbound reference (L-011).
  it.each([
    ['autogenerated token', 'air_superiority', 'Air Superiority'],
    ['custom token', 'tech_spitfire_equipment_1', 'Supermarine Spitfire'],
  ])(
    'issues no renameTo and no block rename for a %s public-name edit (gate 1)',
    async (_label, token, currentName) => {
      await project(
        localisation({
          entries: [
            {
              key: token,
              permission: 'editable',
              target: LOC_TARGET,
              value: currentName,
              version: '0',
            },
          ],
        }),
        entity(token),
      ).save(values({ __publicName: 'Air Dominance', research_cost: '9' }));

      const request = writeBatch.mock.calls[0][0] as EntityBatchWriteRequest;
      for (const operation of request.operations) {
        expect(operation).not.toHaveProperty('renameTo');
      }
      // The script op still names the UNCHANGED token, and the loc op keys on it.
      expect(request.operations[0]).toMatchObject({
        entityName: token,
        format: 'script',
      });
      expect(request.operations[1]).toMatchObject({
        deltas: [{ key: token, kind: 'set', value: 'Air Dominance' }],
        format: 'loc',
      });
    },
  );

  it('writes no script operation at all when only the public name changed (gate 1)', async () => {
    await project().save(values({ __publicName: 'Air Dominance' }));

    const request = writeBatch.mock.calls[0][0] as EntityBatchWriteRequest;
    expect(request.operations.map((operation) => operation.format)).toEqual([
      'loc',
    ]);
  });

  it('writes nothing when neither half changed', async () => {
    await project().save(values());

    expect(writeBatch).not.toHaveBeenCalled();
  });
});

describe('technology form — save-time confirmations (gate 7)', () => {
  it('preserves the ADR 022 `@NAME` warning', () => {
    const confirm = project().confirmBeforeSave?.(
      values({
        folder: [
          {
            name: 'air_techs_folder',
            [OBJECT_LIST_ITEM_INDEX_KEY]: 0,
            position: { x: '10', y: '4' },
          },
        ],
      }),
    );

    expect(confirm?.message).toContain('@FTR_START → 10');
  });

  it('does not prompt about a token rename — the edit path issues none (gate 1)', () => {
    const confirm = project().confirmBeforeSave?.(
      values({ __publicName: 'Air Dominance' }),
    );

    expect(confirm).toBeNull();
  });

  it('does not prompt when nothing symbolic moves and the token is stable', () => {
    const confirm = project(
      localisation({
        entries: [
          {
            key: 'tech_spitfire_equipment_1',
            permission: 'editable',
            target: LOC_TARGET,
            value: 'Supermarine Spitfire',
            version: '0',
          },
        ],
      }),
      entity('tech_spitfire_equipment_1'),
    ).confirmBeforeSave?.(
      values({ __publicName: 'Supermarine Spitfire Mk.V' }),
    );

    expect(confirm).toBeNull();
  });
});
