import { EntityFormLocalisationContext } from '@r-core';
import { describe, expect, it } from 'vitest';

import {
  computeTechnologyLocPlan,
  technologyPublicName,
} from './technology-loc-delta.util';

// ZMT-50 regression gates 4 and 5 — the ADR 028 decision 4 pivot, both branches.
// Fixtures mirror real BICE shapes: an autogen-shaped doctrine tech
// (`air_superiority` ↔ "Air Superiority", `research_l_english.yml:547`) and a
// custom-token equipment tech (`tech_spitfire_equipment_1` ↔ "Supermarine
// Spitfire", `equipment_l_english_Commonwealth.yml:2332`).

const BICE = {
  modId: 'bice',
  relativePath: 'localisation/english/research_l_english.yml',
};
const DEFAULT_TARGET = {
  modId: 'bice',
  relativePath: 'localisation/english/BI_Characters_l_english.yml',
};

function context(
  entries: EntityFormLocalisationContext['entries'],
  takenIds: readonly string[] = [],
): EntityFormLocalisationContext {
  return { defaultTarget: DEFAULT_TARGET, entries, takenIds };
}

describe('computeTechnologyLocPlan — custom token (gate 5)', () => {
  const entries = [
    {
      key: 'tech_spitfire_equipment_1',
      permission: 'editable' as const,
      target: BICE,
      value: 'Supermarine Spitfire',
      version: '0',
    },
  ];

  it('does a loc `set` on the existing key, with NO stale delete', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(entries), token: 'tech_spitfire_equipment_1' },
      'Supermarine Spitfire Mk.V',
      'Supermarine Spitfire',
    );

    expect(plan.renameTo).toBeUndefined();
    expect(plan.movedKeys).toEqual([]);
    expect(plan.operations).toEqual([
      {
        deltas: [
          {
            key: 'tech_spitfire_equipment_1',
            kind: 'set',
            value: 'Supermarine Spitfire Mk.V',
          },
        ],
        format: 'loc',
        modId: 'bice',
        relativePath: 'localisation/english/research_l_english.yml',
      },
    ]);
  });

  it('emits nothing at all when the public name is unchanged', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(entries), token: 'tech_spitfire_equipment_1' },
      'Supermarine Spitfire',
      'Supermarine Spitfire',
    );

    expect(plan.operations).toEqual([]);
    expect(plan.renameTo).toBeUndefined();
  });
});

describe('computeTechnologyLocPlan — autogenerated token (gate 4)', () => {
  const entries = [
    {
      key: 'air_superiority',
      permission: 'editable' as const,
      target: BICE,
      value: 'Air Superiority',
      version: '0',
    },
    {
      key: 'air_superiority_desc',
      permission: 'editable' as const,
      target: BICE,
      value: 'Achieving Air Superiority will make it more difficult…',
      version: '0',
    },
  ];

  it('deletes the stale key and inserts the new one, in ONE operation on the owning file', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(entries), token: 'air_superiority' },
      'Air Dominance',
      'Air Superiority',
    );

    expect(plan.renameTo).toBe('air_dominance');
    expect(plan.movedKeys).toEqual(['air_superiority', 'air_superiority_desc']);
    // One operation, because both keys live in the same `.yml` and one operation
    // owns one file — two would each stage from the on-disk original.
    expect(plan.operations).toHaveLength(1);
    expect(plan.operations[0].deltas).toEqual([
      { key: 'air_superiority', kind: 'delete' },
      {
        key: 'air_dominance',
        kind: 'insert',
        value: 'Air Dominance',
        version: '0',
      },
      { key: 'air_superiority_desc', kind: 'delete' },
      {
        key: 'air_dominance_desc',
        kind: 'insert',
        value: 'Achieving Air Superiority will make it more difficult…',
        version: '0',
      },
    ]);
  });

  it('suffixes the regenerated token past a collision rather than rejecting', () => {
    const plan = computeTechnologyLocPlan(
      {
        context: context(entries, ['air_dominance', 'air_superiority']),
        token: 'air_superiority',
      },
      'Air Dominance',
      'Air Superiority',
    );

    expect(plan.renameTo).toBe('air_dominance_2');
    expect(plan.operations[0].deltas).toContainEqual({
      key: 'air_dominance_2',
      kind: 'insert',
      value: 'Air Dominance',
      version: '0',
    });
  });

  it('moves only the derived keys that are actually present', () => {
    const plan = computeTechnologyLocPlan(
      { context: context([entries[0]]), token: 'air_superiority' },
      'Air Dominance',
      'Air Superiority',
    );

    expect(plan.movedKeys).toEqual(['air_superiority']);
    expect(plan.operations[0].deltas).toHaveLength(2);
  });
});

describe('computeTechnologyLocPlan — no existing key (ZMT-50 grounding §4)', () => {
  // None of the 35 base `air_techs_folder` technologies the canvas renders has a
  // BICE loc key: their names live in vanilla. ADR 028 does not name this case; it
  // is the COMMON one on the PoC folder.
  it('inserts into the default target (the ADR 028 D6 seam)', () => {
    const plan = computeTechnologyLocPlan(
      { context: context([]), token: 'fighter1' },
      'Interwar Fighter',
      '',
    );

    expect(plan.renameTo).toBeUndefined();
    expect(plan.operations).toEqual([
      {
        deltas: [
          {
            key: 'fighter1',
            kind: 'insert',
            value: 'Interwar Fighter',
            version: '0',
          },
        ],
        format: 'loc',
        modId: 'bice',
        relativePath: 'localisation/english/BI_Characters_l_english.yml',
      },
    ]);
  });

  it('inserts an override instead of writing a readonly (vanilla) key', () => {
    const plan = computeTechnologyLocPlan(
      {
        context: context([
          {
            key: 'fighter1',
            permission: 'readonly',
            target: null,
            value: 'Fighter I',
            version: '0',
          },
        ]),
        token: 'fighter1',
      },
      'Interwar Fighter',
      'Fighter I',
    );

    expect(plan.operations[0].deltas).toEqual([
      {
        key: 'fighter1',
        kind: 'insert',
        value: 'Interwar Fighter',
        version: '0',
      },
    ]);
    expect(plan.operations[0].relativePath).toBe(
      'localisation/english/BI_Characters_l_english.yml',
    );
  });

  it('drops the edit rather than guessing when there is no editable loc file', () => {
    const plan = computeTechnologyLocPlan(
      {
        context: { defaultTarget: null, entries: [], takenIds: [] },
        token: 'fighter1',
      },
      'Interwar Fighter',
      '',
    );

    expect(plan.operations).toEqual([]);
  });
});

describe('technologyPublicName', () => {
  it('reads the name key value', () => {
    expect(
      technologyPublicName(
        context([
          {
            key: 'air_superiority',
            permission: 'editable',
            target: BICE,
            value: 'Air Superiority',
            version: '0',
          },
        ]),
        'air_superiority',
      ),
    ).toBe('Air Superiority');
  });

  it('is empty when no source defines the key', () => {
    expect(technologyPublicName(context([]), 'fighter1')).toBe('');
  });
});
