import { EntityFormLocalisationContext } from '@r-core';
import { describe, expect, it } from 'vitest';

import {
  computeTechnologyLocPlan,
  technologyPublicName,
} from './technology-loc-delta.util';

// ZMT-50 fix-pass gates 1 and 2 — the token is FROZEN on the edit path, so BOTH
// token states write the current token's key and NEITHER renames the block.
// Fixtures mirror real BICE shapes: an autogen-shaped doctrine tech
// (`air_superiority` ↔ "Air Superiority", `research_l_english.yml:547`), a
// custom-token equipment tech (`tech_spitfire_equipment_1` ↔ "Supermarine
// Spitfire", `equipment_l_english_Commonwealth.yml:2332`), and a base air tech
// with no BICE key at all (`fighter1` — its name lives in vanilla).

const BICE = {
  modId: 'bice',
  relativePath: 'localisation/english/research_l_english.yml',
};
const DEFAULT_TARGET = {
  modId: 'bice',
  relativePath: 'localisation/english/BI_Characters_l_english.yml',
};

function context(
  entries: EntityFormLocalisationContext['entries'],
  takenIds: readonly string[] = [],
): EntityFormLocalisationContext {
  return {
    defaultTarget: DEFAULT_TARGET,
    defaultTargetSeedLanguage: null,
    entries,
    takenIds,
  };
}

const AUTOGEN_ENTRIES = [
  {
    key: 'air_superiority',
    permission: 'editable' as const,
    target: BICE,
    value: 'Air Superiority',
    version: '0',
  },
  {
    key: 'air_superiority_desc',
    permission: 'editable' as const,
    target: BICE,
    value: 'Achieving Air Superiority will make it more difficult…',
    version: '0',
  },
];

const CUSTOM_ENTRIES = [
  {
    key: 'tech_spitfire_equipment_1',
    permission: 'editable' as const,
    target: BICE,
    value: 'Supermarine Spitfire',
    version: '0',
  },
];

describe('computeTechnologyLocPlan — custom token (gate 2)', () => {
  it('does a loc `set` on the existing key, with NO stale delete', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(CUSTOM_ENTRIES), token: 'tech_spitfire_equipment_1' },
      'Supermarine Spitfire Mk.V',
      'Supermarine Spitfire',
    );

    expect(plan.operations).toEqual([
      {
        deltas: [
          {
            key: 'tech_spitfire_equipment_1',
            kind: 'set',
            value: 'Supermarine Spitfire Mk.V',
          },
        ],
        format: 'loc',
        modId: 'bice',
        relativePath: 'localisation/english/research_l_english.yml',
      },
    ]);
  });

  it('emits nothing at all when the public name is unchanged', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(CUSTOM_ENTRIES), token: 'tech_spitfire_equipment_1' },
      'Supermarine Spitfire',
      'Supermarine Spitfire',
    );

    expect(plan.operations).toEqual([]);
  });
});

describe('computeTechnologyLocPlan — autogenerated token, token frozen (gates 1 and 2)', () => {
  // `air_superiority` IS autogen-shaped (`token === normalize(name)`), the state
  // ADR 028 D4 said would regenerate the token. On the edit path it must not:
  // regenerating orphans every inbound reference, which is L-011's cascade.
  it('does a loc `set` on the CURRENT token’s key — no delete-then-insert under a new token', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(AUTOGEN_ENTRIES), token: 'air_superiority' },
      'Air Dominance',
      'Air Superiority',
    );

    expect(plan.operations).toEqual([
      {
        deltas: [
          { key: 'air_superiority', kind: 'set', value: 'Air Dominance' },
        ],
        format: 'loc',
        modId: 'bice',
        relativePath: 'localisation/english/research_l_english.yml',
      },
    ]);
  });

  it('issues no delete of any kind, so no loc key is ever orphaned by an edit (gate 1)', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(AUTOGEN_ENTRIES), token: 'air_superiority' },
      'Air Dominance',
      'Air Superiority',
    );

    expect(
      plan.operations.flatMap((operation) => operation.deltas),
    ).not.toContainEqual(expect.objectContaining({ kind: 'delete' }));
  });

  it('leaves the derived `_desc` key alone — it still keys on the unchanged token', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(AUTOGEN_ENTRIES), token: 'air_superiority' },
      'Air Dominance',
      'Air Superiority',
    );

    expect(
      plan.operations
        .flatMap((operation) => operation.deltas)
        .map((delta) => delta.key),
    ).toEqual(['air_superiority']);
  });

  it('carries no rename — the plan type has no field to carry one (gate 1)', () => {
    const plan = computeTechnologyLocPlan(
      { context: context(AUTOGEN_ENTRIES), token: 'air_superiority' },
      'Air Dominance',
      'Air Superiority',
    );

    expect(plan).not.toHaveProperty('renameTo');
    expect(Object.keys(plan)).toEqual(['operations']);
  });

  it('is unaffected by a would-be token collision — nothing derives a token here', () => {
    const plan = computeTechnologyLocPlan(
      {
        context: context(AUTOGEN_ENTRIES, ['air_dominance', 'air_superiority']),
        token: 'air_superiority',
      },
      'Air Dominance',
      'Air Superiority',
    );

    expect(plan.operations[0].deltas).toEqual([
      { key: 'air_superiority', kind: 'set', value: 'Air Dominance' },
    ]);
  });
});

describe('computeTechnologyLocPlan — no existing key (grounding §4, gate 2)', () => {
  // None of the 35 base `air_techs_folder` technologies the canvas renders has a
  // BICE loc key: their names live in vanilla. ADR 028 D4 enumerated set and
  // delete; this first-save INSERT is the third case, and the common one here.
  it('inserts on the current token’s key into the default target (the ADR 028 D6 seam)', () => {
    const plan = computeTechnologyLocPlan(
      { context: context([]), token: 'fighter1' },
      'Interwar Fighter',
      '',
    );

    expect(plan.operations).toEqual([
      {
        deltas: [
          {
            key: 'fighter1',
            kind: 'insert',
            value: 'Interwar Fighter',
            version: '0',
          },
        ],
        format: 'loc',
        modId: 'bice',
        relativePath: 'localisation/english/BI_Characters_l_english.yml',
      },
    ]);
  });

  it('inserts an override instead of writing a readonly (vanilla) key', () => {
    const plan = computeTechnologyLocPlan(
      {
        context: context([
          {
            key: 'fighter1',
            permission: 'readonly',
            target: null,
            value: 'Fighter I',
            version: '0',
          },
        ]),
        token: 'fighter1',
      },
      'Interwar Fighter',
      'Fighter I',
    );

    expect(plan.operations[0].deltas).toEqual([
      {
        key: 'fighter1',
        kind: 'insert',
        value: 'Interwar Fighter',
        version: '0',
      },
    ]);
    expect(plan.operations[0].relativePath).toBe(
      'localisation/english/BI_Characters_l_english.yml',
    );
  });

  // ZMT-57 gate 2, the write half: the insert target is whatever
  // `resolveWriteTarget('locKey', …)` returned upstream, and a CHOSEN one is paired
  // with its create-if-absent seed inside the same batch (ADR 029 decisions 3, 6).
  it('leads the insert with a locCreate when the target is the user’s chosen file', () => {
    const plan = computeTechnologyLocPlan(
      {
        context: {
          defaultTarget: {
            modId: 'bice',
            relativePath: 'localisation/english/zmt_new_l_english.yml',
          },
          defaultTargetSeedLanguage: 'english',
          entries: [],
          takenIds: [],
        },
        token: 'fighter1',
      },
      'Interwar Fighter',
      '',
    );

    expect(plan.operations).toEqual([
      {
        format: 'locCreate',
        language: 'english',
        modId: 'bice',
        relativePath: 'localisation/english/zmt_new_l_english.yml',
      },
      {
        deltas: [
          {
            key: 'fighter1',
            kind: 'insert',
            value: 'Interwar Fighter',
            version: '0',
          },
        ],
        format: 'loc',
        modId: 'bice',
        relativePath: 'localisation/english/zmt_new_l_english.yml',
      },
    ]);
  });

  // The scope line of ADR 029 decision 2: an existing editable key is a `set` on the
  // file that OWNS it — provenance-routed, never save-target-routed — so a chosen
  // target does not pull it out of its own file.
  it('still writes an existing editable key to its owning file, never to the chosen target', () => {
    const plan = computeTechnologyLocPlan(
      {
        context: {
          defaultTarget: {
            modId: 'bice',
            relativePath: 'localisation/english/zmt_new_l_english.yml',
          },
          defaultTargetSeedLanguage: 'english',
          entries: AUTOGEN_ENTRIES,
          takenIds: [],
        },
        token: 'air_superiority',
      },
      'Air Supremacy',
      'Air Superiority',
    );

    expect(plan.operations).toEqual([
      {
        deltas: [
          { key: 'air_superiority', kind: 'set', value: 'Air Supremacy' },
        ],
        format: 'loc',
        modId: BICE.modId,
        relativePath: BICE.relativePath,
      },
    ]);
  });

  it('drops the edit rather than guessing when there is no editable loc file', () => {
    const plan = computeTechnologyLocPlan(
      {
        context: {
          defaultTarget: null,
          defaultTargetSeedLanguage: null,
          entries: [],
          takenIds: [],
        },
        token: 'fighter1',
      },
      'Interwar Fighter',
      '',
    );

    expect(plan.operations).toEqual([]);
  });
});

describe('technologyPublicName', () => {
  it('reads the name key value', () => {
    expect(
      technologyPublicName(context(AUTOGEN_ENTRIES), 'air_superiority'),
    ).toBe('Air Superiority');
  });

  it('is empty when no source defines the key', () => {
    expect(technologyPublicName(context([]), 'fighter1')).toBe('');
  });
});
