import type { LocDelta } from '../localisation';
import type { ModId } from '../workspace';
import type { EntityBlockDelta } from './entity-write.model';

// One operation of a cross-file atomic batch (ADR 027 decision 1: a write is
// `{ file, format, delta }`). `format` is the routing key to the format strategy;
// the file is addressed as `modId` + mod-relative path exactly as
// `EntityWriteRequest` does, so the renderer never names an absolute path and the
// main side resolves and path-guards it unchanged.
export type EntityBatchOperation =
  | EntityLocBatchOperation
  | EntityScriptBatchOperation;

// `entity:writeBatch` — the ADR 027 cross-file batch surfaced over IPC, so a
// single Save can span a Clausewitz `.txt` and a localisation `.yml` atomically
// (ADR 028 decision 1). `entity:write` is unchanged and still serves the six other
// entity forms and the mod descriptor: this is an ADDITIONAL channel, not a
// replacement.
export interface EntityBatchWriteRequest {
  readonly operations: readonly EntityBatchOperation[];
}

// ORDERED deltas against one `.yml`. A list, not a single delta, because an
// autogenerated-token rename deletes the stale key and inserts the new one and in
// BICE both usually live in the same file (ADR 028 decision 4) — and one operation
// owns one file, so they cannot be split into two operations.
export interface EntityLocBatchOperation {
  readonly deltas: readonly LocDelta[];
  readonly format: 'loc';
  readonly modId: ModId;
  readonly relativePath: string;
}

export interface EntityScriptBatchOperation {
  readonly deltas: readonly EntityBlockDelta[];
  readonly entityName: string;
  readonly format: 'script';
  readonly modId: ModId;
  readonly relativePath: string;
  // Renames the entity's own block head in the same edit pass. DORMANT — no
  // production caller emits it (ZMT-50 review, Q89/Q90). It renames the block ONLY;
  // references to the old name elsewhere in the corpus are not rewritten, so a
  // rename issued without the deferred reference cascade (ledger L-011, its own
  // ADR) leaves dangling references. The technology edit form freezes the token
  // precisely so it can never reach this field.
  readonly renameTo?: string;
}
