import type { LocDelta } from '../localisation';
import type { ModId } from '../workspace';
import type { EntityBlockDelta } from './entity-write.model';

// One operation of a cross-file atomic batch (ADR 027 decision 1: a write is
// `{ file, format, delta }`). `format` is the routing key to the format strategy;
// the file is addressed as `modId` + mod-relative path exactly as
// `EntityWriteRequest` does, so the renderer never names an absolute path and the
// main side resolves and path-guards it unchanged.
export type EntityBatchOperation =
  | EntityLocBatchOperation
  | EntityLocCreateBatchOperation
  | EntityScriptBatchOperation
  | EntityScriptCreateBatchOperation
  | EntityScriptDeleteBatchOperation;

// `entity:writeBatch` — the ADR 027 cross-file batch surfaced over IPC, so a
// single Save can span a Clausewitz `.txt` and a localisation `.yml` atomically
// (ADR 028 decision 1). `entity:write` is unchanged and still serves the six other
// entity forms and the mod descriptor: this is an ADDITIONAL channel, not a
// replacement.
export interface EntityBatchWriteRequest {
  readonly operations: readonly EntityBatchOperation[];
}

// ORDERED deltas against one `.yml`. A list, not a single delta, because an
// autogenerated-token rename deletes the stale key and inserts the new one and in
// BICE both usually live in the same file (ADR 028 decision 4) — and one operation
// owns one file, so they cannot be split into two operations.
export interface EntityLocBatchOperation {
  readonly deltas: readonly LocDelta[];
  readonly format: 'loc';
  readonly modId: ModId;
  readonly relativePath: string;
}

// CREATE the localisation `.yml` this addresses, seeded with the UTF-8 BOM and the
// `l_<language>:` header (ZMT-56, the amendment ADR 029 decision 6 requires of ADR
// 027 decision 3). `language` is the header's language and matches the target's
// own `_l_<language>` filename suffix; the caller owns that consistency, exactly as
// it does for every existing loc write.
export interface EntityLocCreateBatchOperation {
  readonly format: 'locCreate';
  readonly language: string;
  readonly modId: ModId;
  readonly relativePath: string;
}

export interface EntityScriptBatchOperation {
  readonly deltas: readonly EntityBlockDelta[];
  readonly entityName: string;
  readonly format: 'script';
  // Turns the operation into an ADR 027 decision 4 INSERT (closing ledger L-012):
  // `entityName` is CREATED as a new named block under the existing block this
  // names (`technologies` for a technology file) instead of patching an existing
  // one, and `deltas` are read as the new block's body — only their `added` and
  // `block` fields, since a block that does not exist yet has nothing to change or
  // remove. Absent → the patch semantics every pre-ZMT-51 caller has.
  //
  // Mutually exclusive with `renameTo`: renaming a block that is being created in
  // the same breath is incoherent, and the pair would silently resolve to one of
  // the two. The handler rejects both together rather than picking.
  readonly insertUnder?: string;
  readonly modId: ModId;
  readonly relativePath: string;
  // Renames the entity's own block head in the same edit pass. DORMANT — no
  // production caller emits it (ZMT-50 review, Q89/Q90). It renames the block ONLY;
  // references to the old name elsewhere in the corpus are not rewritten, so a
  // rename issued without the deferred reference cascade (ledger L-011, its own
  // ADR) leaves dangling references. The technology edit form freezes the token
  // precisely so it can never reach this field.
  readonly renameTo?: string;
}

// CREATE the Clausewitz `.txt` this addresses (ZMT-56, the amendment ADR 029
// decision 6 requires of ADR 027 decision 3). `rootBlocks` are the wrapper blocks
// the seed carries — `['technologies']` for a technology file — because the AST
// insert addresses a PARENT BLOCK and not a file position (ADR 027 decision 4), and
// an empty file, though perfectly parseable, gives it nothing to find. It is
// therefore per WRITE-KIND, which is the second thing a kind registers after its
// folder (ADR 029 decision 3).
//
// Both create operations are create-IF-ABSENT: a target that already exists is
// read and patched exactly as any other operation's is, and only a file the batch
// genuinely brought into being rolls back by UNLINK. Like `scriptDelete`, they are
// SEPARATE union members discriminated on `format` rather than a flag on the
// content operations: a create carries a seed and no deltas, and folding it in
// would make every field of both optional. `format` still names the routing key of
// the strategy that owns the seed's byte shape.
export interface EntityScriptCreateBatchOperation {
  readonly format: 'scriptCreate';
  readonly modId: ModId;
  readonly relativePath: string;
  readonly rootBlocks: readonly string[];
}

// N block DELETIONS against ONE `.txt`, applied in the listed order (ZMT-52).
// A list, not a single name, for exactly the reason the loc operation carries a
// list: one operation owns one file (`assertOneOperationPerFile`), and
// delete-tree routinely removes several technologies that live in the same file —
// all 35 base `air_techs_folder` technologies live in one `air_techs.txt`. Two
// operations on that path would each stage from the on-disk original, so the
// second temp-write would silently drop the first's deletion.
//
// It is a SEPARATE union member rather than a `kind` on the script operation
// because a delete carries no field deltas, no `insertUnder`, no `renameTo` and
// no single `entityName`: the two shapes share nothing but the file address, and
// folding them together would make every field of both optional. `format` still
// routes to the AST strategy — `scriptDelete` is the same Clausewitz family as
// `script`; what differs is the DELTA KIND, not the format.
export interface EntityScriptDeleteBatchOperation {
  readonly entityNames: readonly string[];
  readonly format: 'scriptDelete';
  readonly modId: ModId;
  readonly relativePath: string;
}
