import { ModalConfirmOptions } from '../modal';
import { TranslateFn } from '../recognizer';
import { EntityFormBlock } from './entity-form-block.model';

// A per-(game, entity) form descriptor. Mirrors the read-side recognizer as a
// code module, registered host-side and kept separate from the recognizer
// registry; the two share only the entity-identifier constant (`entityId` ===
// the recognizer's `id`). Concrete descriptors live in the per-game library.
// `project` accepts the subject type-erased so the host registry can store and
// invoke descriptors uniformly; use `defineEntityFormDescriptor` for a
// subject-typed projection.
export interface EntityFormDescriptor {
  readonly entityId: string;
  readonly gameId: string;
  readonly project: (
    subject: unknown,
    context: EntityFormProjectContext,
  ) => EntityFormModel;
}

// Localisation the host resolved BEFORE projecting, for a descriptor whose form
// edits a localised field (ADR 028 decision 3). Optional: a descriptor with no loc
// field never reads it, and the six other entity forms pass nothing.
export interface EntityFormLocalisationContext {
  // Where a key with no existing owner is inserted — the ADR 028 decision 6 seam
  // (`resolveWriteTarget` / save-target settings replace it later). Null when the
  // workspace has no editable localisation file at all, which disables the field.
  readonly defaultTarget: EntityFormLocTarget | null;
  readonly entries: readonly EntityFormLocEntry[];
  // Entity ids already taken across the workspace, for autogenerated-token
  // collision handling (ledger L-023: suffix, never reject).
  readonly takenIds: readonly string[];
}

// One localisation key the host already resolved for the subject: its current
// value, the file that owns it, and whether that file may be written. `target` is
// null when the winning definition lives in a source with no writable identity
// (vanilla) — a rename of such a key is an insert into `defaultTarget`, not a set.
export interface EntityFormLocEntry {
  readonly key: string;
  readonly permission: 'editable' | 'readonly';
  readonly target: EntityFormLocTarget | null;
  readonly value: string;
  readonly version: string;
}

// A writable localisation file: the owning mod plus a mod-relative path. Declared
// structurally here rather than imported, because r-core carries no @contracts
// dependency — the host passes the already-resolved values in.
export interface EntityFormLocTarget {
  readonly modId: string;
  readonly relativePath: string;
}

// The shell's single, entity-agnostic input. A descriptor projects a domain
// entity into this; the host's mod-descriptor view builds it directly. The
// shell renders the blocks, wires RHF, tracks dirty, runs the resolver, guards
// unsaved changes, and dispatches `save` — carrying no entity-specific
// knowledge of its own.
export interface EntityFormModel {
  readonly blocks: readonly EntityFormBlock[];
  // Optional save-time gate. Returns the confirm-dialog options to show BEFORE
  // persisting — e.g. a field bound to a `@NAME` substitution constant that a
  // literal edit would replace, breaking the binding (ADR 022, decision 6) — or
  // `null` to save without prompting. The shell shows the confirm and aborts the
  // save when the user cancels. Descriptor-owned: it names what is being replaced.
  readonly confirmBeforeSave?: (
    values: EntityFormValues,
  ) => ModalConfirmOptions | null;
  // Resolved title for the modal-dialog form chrome (entity name).
  readonly dialogTitle?: string;
  // Resolved error chrome. `errorMessage` maps an IpcError numeric code to a
  // user-facing string (display-layer mapping per R-CODE-5, not invention).
  readonly errorMessage: (code: number) => string;
  readonly errorTitle: string;
  // Resolved muted note beside the dialog title (e.g. a module's category).
  readonly note?: string;
  // Persist edited values. Rejects with an IpcError on failure. The shell
  // awaits this, clears dirty on success, and surfaces the error while keeping
  // dirty on failure. May return the next values to reset to (a reparse
  // round-trip); otherwise the shell resets to the submitted values.
  readonly save: (values: EntityFormValues) => Promise<EntityFormValues | void>;
  // Externally-supplied Zod schema (the mod-descriptor plugin-extension path).
  // Typed `unknown` to keep r-core free of a Zod dependency — the shell casts
  // to its resolver input. Absent → the shell generates a schema from the
  // blocks' field specs.
  readonly schema?: () => unknown;
}

// Capabilities the host supplies to a descriptor's projection at present time.
export interface EntityFormProjectContext {
  readonly localisation?: EntityFormLocalisationContext;
  // Which side of the ADR 028 decision 5 shared model this projection is for. The
  // SAME descriptor and the SAME blocks serve both; only the subject and the write
  // differ — `add` projects over a seeded blank subject and saves as an INSERT of a
  // new entity, `edit` (the default, and what every pre-ZMT-51 caller means) diffs
  // against a real subject and saves as a patch. A descriptor with no create path
  // ignores it.
  readonly mode?: 'add' | 'edit';
  readonly modId: string;
  readonly relativePath: string;
  readonly translate: TranslateFn;
}

// The flat RHF value object. Keys are block bindings: a field-array name for
// open / named-nested bags and list blocks, a root field name for each fixed
// field. The descriptor that built the blocks owns the shape on save.
export type EntityFormValues = Readonly<Record<string, unknown>>;

// Builds a descriptor with a subject-typed `project` while keeping the stored
// shape type-erased. The recast is contained here — the descriptor is only ever
// invoked with the subject the matching recognizer produced.
export function defineEntityFormDescriptor<TSubject>(descriptor: {
  readonly entityId: string;
  readonly gameId: string;
  readonly project: (
    subject: TSubject,
    context: EntityFormProjectContext,
  ) => EntityFormModel;
}): EntityFormDescriptor {
  return {
    entityId: descriptor.entityId,
    gameId: descriptor.gameId,
    project: (subject, context) =>
      descriptor.project(subject as TSubject, context),
  };
}
