import type {
  IndexSlimRow,
  SourcesTable,
  TechnologySlim,
  TechTreeFolderGeometry,
} from '@contracts';
import type { Edge } from '@xyflow/react';

import { useCallback, useEffect, useState } from 'react';

import { entityIndexClient } from '../../../shared/entity-index';
import { techTreeGeometryClient } from '../../../shared/tech-tree-geometry';
import { buildAirTreeFlow, TechFlowNode } from '../build-air-tree-flow.util';

// The PoC air tree is the base plane tree, which lives entirely in this one
// folder (ZMT-43 grounding: every base air tech's `folder.name` is this, and the
// country trees are separate folders). Hardcoded because the `aircraft` feature
// IS this surface; a country switch (later) parameterizes it.
export const AIR_TECHS_FOLDER = 'air_techs_folder';

export interface AirTechTree extends AirTechTreeSnapshot {
  // Re-runs the fetch. Add and Edit write through the main side, so the held
  // snapshot is stale the moment a save lands; the writer calls this rather than
  // the hook polling or a store subscribing (L-005 stays closed).
  readonly reload: () => void;
}

interface AirTechTreeSnapshot {
  // Every technology id in the workspace, not just this folder's — the edit form
  // needs the whole set to suffix an autogenerated token past a collision (L-023).
  readonly allTechnologyIds: readonly string[];
  // The `dependencies` overlay (off by default; the canvas shows it on toggle).
  readonly dependencyEdges: readonly Edge[];
  readonly edges: readonly Edge[];
  // The folder's render geometry, null until loaded or when the `.gui` declares no
  // such folder. Add needs it directly — the built nodes carry pixels, but placing
  // a NEW node needs the gridbox origins, steps, and the year gutter (ZMT-51).
  readonly folder: null | TechTreeFolderGeometry;
  readonly nodes: readonly TechFlowNode[];
  // The folder's slim rows with their provenance — what Add joins through
  // `sources` to reach the owning mod and the `.txt` a new technology is written
  // into. The built `nodes` cannot answer that: they carry pixels, not files.
  readonly rows: readonly IndexSlimRow<TechnologySlim>[];
  // The companion sources table (ADR 024 decision 3): the edit form joins a node's
  // `provenance.sourceId` through it to reach the owning mod.
  readonly sources: SourcesTable;
  readonly status: AirTechTreeStatus;
}

type AirTechTreeStatus = 'error' | 'loading' | 'ready';

const EMPTY: AirTechTreeSnapshot = {
  allTechnologyIds: [],
  dependencyEdges: [],
  edges: [],
  folder: null,
  nodes: [],
  rows: [],
  sources: {},
  status: 'loading',
};

// Fetches `index:list('technology')` + `techTreeGeometry:read` once, scopes the
// slim rows to `air_techs_folder` (plus the subs those techs attach), and holds
// the built react-flow graph in React state — no store, no data-fetching library
// (ADR 026 decision 2, L-005 closed). Server state is fetch-once-hold against the
// main-side cache.
export function useAirTechTree(): AirTechTree {
  const [state, setState] = useState<AirTechTreeSnapshot>(EMPTY);
  const [version, setVersion] = useState(0);
  const reload = useCallback(() => {
    setVersion((previous) => previous + 1);
  }, []);

  useEffect(() => {
    let cancelled = false;

    Promise.all([
      entityIndexClient.list('technology'),
      techTreeGeometryClient.read(),
    ])
      .then(([list, geometry]) => {
        if (cancelled) {
          return;
        }
        const allTechnologyIds = list.rows.map((row) => row.slim.id);
        const folder = geometry.folders[AIR_TECHS_FOLDER] ?? null;
        if (folder === null) {
          setState({
            allTechnologyIds,
            dependencyEdges: [],
            edges: [],
            folder,
            nodes: [],
            rows: [],
            sources: list.sources,
            status: 'ready',
          });
          return;
        }
        const airRows = list.rows.filter(
          (row) => row.slim.folderName === AIR_TECHS_FOLDER,
        );
        const air = airRows.map((row) => row.slim);
        const subIds = new Set(air.flatMap((slim) => slim.subTechnologies));
        const subs = list.rows
          .map((row) => row.slim)
          .filter((slim) => slim.position === null && subIds.has(slim.id));
        const { dependencyEdges, edges, nodes } = buildAirTreeFlow(
          [...air, ...subs],
          folder,
        );
        setState({
          allTechnologyIds,
          dependencyEdges,
          edges,
          folder,
          nodes,
          rows: airRows,
          sources: list.sources,
          status: 'ready',
        });
      })
      .catch(() => {
        if (!cancelled) {
          setState({ ...EMPTY, status: 'error' });
        }
      });

    return () => {
      cancelled = true;
    };
  }, [version]);

  return { ...state, reload };
}
